### PR TITLE
Terminal now inherits colors from syntax theme

### PR DESCRIPTION
**Pull request by acondiff**

### CODE REVIEW

**Comment by acondiff** [comment]
I would at some point create some configurable package options like so...
```
{
    useSyntaxTheme: true|false,
    useEditorFont: true|false,
    // IF ABOVE ARE FALSE THEN USE BELOW OPTIONS...
    fontSize: 14,
    // font family with optional fallbacks
    fontFamily: '"Apercu Mono", "Roboto Mono", Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',
    // terminal cursor background color
    cursorColor: '#1BA3EA',
    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BEAM',
    // color of the text
    foregroundColor: '#ffffff',
    // terminal background color
    backgroundColor: '#171717',
    colors: {
      black:        '#000000',
      red:          '#e06c75',
      green:        '#A3F674',
      yellow:       '#FFC235',
      blue:         '#1EBBFF',
      magenta:      '#FF5BA9',
      cyan:         '#A78EFF',
      white:        '#d0d0d0',
      lightBlack:   '#808080',
      lightRed:     '#e06c75',
      lightGreen:   '#A3F674',
      lightYellow:  '#FFC235',
      lightBlue:    '#82DDFF',
      lightMagenta: '#FF5BA9',
      lightCyan:    '#A78EFF',
      lightWhite:   '#ffffff'
    }
}
```

**Comment by jsmecham** [comment]
This is awesome! We need to support themes that don't have certain variables defined, however. For example, with Atom Dark I am seeing the following:

error

**Comment by acondiff** [comment]
Oh, easy peasy. I just need to set some defaults. I was also working on getting it to use the font family, font size, and line height that is set in Atom config. I will take care of this as well.

**Comment by acondiff** [comment]
I'd really like to help make this as extensive as Hyper if we can, as I described above. I am open to helping you build and maintain this if you would like.

**Comment by acondiff** [comment]
Done. You can check it out now. One todo item I will get to when I have time: I'd like the styles to update when the config changes.

**Comment by acondiff** [comment]
Just a reminder... did you want to look at this again?

**Comment by jsmecham** [comment]
Absolutely! I should have some time later today to look at this again. Thanks again for the contributions!

**Pull request merged**
