### PR TITLE
Initial work on platform-specific keybindings

### PR DESCRIPTION
**Pull request by sogaiu**
Please consider platform-specific keybindings, given the use of the command key in the existing bindings.  Thanks :)

### CODE REVIEW

**Comment by aravindet** [comment]
- Ctrl+C is commonly used to exit command-line applications (such as watch-mode build/test scripts) and should not be trapped in terminal. I suggest Ctrl+Shift+C as the alternative (this is the default in gnome-terminal and probably many other terminals in Linux-land).

- For consistency, it should be Ctrl+Shift-V for paste.

- Several command-line applications might also use Ctrl+K, Ctrl+W etc. For example the popular command line editor nano by default uses Ctrl+K for cut line and Ctrl+W for find. Why would you run a text editor in a terminal in another text editor? Because (for example) git might open it for editing commit messages, interactive rebase, etc. I suggest that they should also be Ctrl+Shift+K and Ctrl+Shift+W.

- I agree with Ctrl+Shift+T for opening the terminal, as it avoids conflicting with Ctrl+T for the fuzzy finder. (Although Ctrl+P also opens the fuzzy finder.)

**Comment by sogaiu** [comment]
I agree that the suggestions (additional Shift modifier for the 5 items) make more sense than what is in the original PR.

@aravindet, perhaps I should just close this PR and you can open a different one instead?

**Comment by aravindet** [comment]
Thanks sogaiu! Please don't close your PR, you can push an update on it.

Thanks,
Aravind

**Comment by sogaiu** [comment]
Updated as requested.  Hope that works.

**Review by aravindet — APPROVED** [review]
Thanks! @jsmecham is this mergeable?

**Pull request closed without merging**
