### PR TITLE
fix issue #7

### PR DESCRIPTION
**Pull request by fradelg**
- put the scrollbar at the right side
- solve focus warning

### CODE REVIEW

**Comment by rapgenic** [comment]
Would it be possible to completely hide the scrollbar as it's shown in the screenshot in the readme? The scrollbar is quite distracting when you use a light theme: a white bar doesn't look very well with the black background, plus it has some visualization issues (see the bottom right corner in the image)

screen

**Comment by jsmecham** [comment]
The scrollbar in the README is on a Mac where "Show scroll bars" is turned off on a system level. I just enabled it on Mac and can replicate this problem now, so I'll get the fix merged.

@rapgenic what platform are you on?

**Comment by jsmecham** [comment]
Thanks, @fradelg!

**Comment by rapgenic** [comment]
@jsmecham sorry for not mentioning, I'm using Arch Linux, with Cinnamon desktop manager, if it can be useful.

**Comment by jsmecham** [comment]
@rapgenic can you give v0.2.2 a try? It should look nicer even on light themes now as I'm replacing the background color to match the Terminal background.

**Comment by rapgenic** [comment]
It's working perfectly now, thank you very much! Keep up the good work :)

_Sent from my Asus Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
