### PR TITLE
Switch to node-pty-prebuilt-multiarch

### LINKED ISSUE #118: Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
And then, rebuild failed, when i rebuild package (image attached).
rebuildfailed

### PR DESCRIPTION
**Pull request by the-j0k3r**
fixes #118

### CODE REVIEW

**Comment by jsmecham** [comment]
Thank you! Will cut a new release this weekend.

**Comment by the-j0k3r** [comment]
@jsmecham you may want to consider merging the other pr's fixing other reported issues before that release =)

**Comment by xavierfoucrier** [comment]
Wow! What a nice fix. Should be perfect :smiley:

**Comment by xavierfoucrier** [comment]
Hi @jsmecham,

How long since the next release?
I am boring using the OS terminal instead of this one :smile:

Thanks!

**Comment by the-j0k3r** [comment]
@jsmecham If you open your Atom `.atom/packages/atom-terminal-tab` folder and delete the `node_modules` directory, then edit the corresponding files as per this PR you can then run `apm i` in that directory and enjoy a working atom-terminal-tab terminal.

**Comment by xavierfoucrier** [comment]
Hi @jsmecham,

I can confirm that the pull request of @the-j0k3r is working fine. I have clone his fork into `.atom/packages`, switched to the branch `fix-node-pty-prebuilt` and run `apm i` to rebuild the package.

The terminal is now running well in Atom.
It's time to **merge and update the package** :wink:

**Comment by jsmecham** [comment]
Fixed in v0.6.0.

**Comment by xavierfoucrier** [comment]
Thanks for the fix @jsmecham! :sunglasses:

**Pull request closed without merging**
